Data Columns and Descriptions
Month (Month)
Bank ATM ID (BANK ATM id)
State (STATE)
Effective Days (Effective days)
Financial Transactions (Fin Txn)
Non-Financial Transactions (Non Fin Txn)
Monthly Transactions (Monthly Txn)
Average Financial Transactions (AVG Fin Txn)
Average Non-Financial Transactions (AVG Non Fin Txn)
Average Total Transactions (AVG Total TXN)
Monthly Revenue (Monthly Rev)
MHA Revenue (MHA Revenue)
ATM Revenue (ATM Rev)
Total CRA (Total CRA)
MHA Cost (MHA Cost)
Spare Replacement (SLM Asset OEM) (Spare Rep. (SLM) (AssetOEM))
Site Maintenance (Non Asset) (Site Maint (Non Asset))
Spare Replacement (AC) (Spare Rep.(AC))
Spare Replacement (UPS) (Spare Rep.(UPS))
Onetime Cost (Onetime Cost)
FLM Supplies (FLM SUPPLIES)
UPS AMC (UPS AMC)
ATM AMC (ATM AMC)
VSAT AMC (VSAT AMC)
Bandwidth and Backhaul (BW + BCKHL)
E-Surveillance (ESURVEILLANCE)
Housekeeping (HK)
Electricity Bill (SUD EBILL)
Rent (RENT)
Insurance (Insurance)
EJ Compensation (EJ Compensation)
Penalty (Penalty)
Total Cost (Total Cost)
Gross Profit (Gross Profit)
Gross Profit Percentage (GROSS PROFIT %)
Quarter (Quarter)
ATM Type (ATM TYPE)
Margin Range (MARGIN RANGE)
Current Month Transaction Range (Current Month TXN RANGE)
Previous Month Transaction Range (Previous Month TXN RANGE)
Previous 2nd Month Transaction Range (Previous 2nd Month TXN RANGE)
Current Margin Range Above/Below 0% (Current Margin Range Above/Below 0%)
Previous Month Margin Range Above/Below 0% (Previous Month Margin Range Above/Below 0%)
Previous 2nd Month Margin Range Above/Below 0% (Previous 2nd Month Margin Range Above/Below 0%)
Previous 3rd Month Margin Range Above/Below 0% (Previous 3rd Month Margin Range Above/Below 0%)
Category (Category)
Revenue Performance (Revenue Performance)
Up Time (Up Time)
